dp-message: fix efidp_node_size() error checking
One of our internal analysis tools noticed the following problems:

 Error: OVERRUN (CWE-119):
 efivar-38/src/dp-message.c:481: return_constant: Function call "efidp_node_size(dp)" may return -1.
 efivar-38/src/dp-message.c:481: assignment: Assigning: "limit" = "(efidp_node_size(dp) - 10UL) / 2UL". The value of "limit" is now 9223372036854775802.
 efivar-38/src/dp-message.c:488: overrun-buffer-arg: Calling "memcpy" with "_asciibuf" and "limit" is suspicious because of the very large index, 9223372036854775802. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
 #  486|                               dp->usb_wwid.vendor_id, dp->usb_wwid.product_id,
 #  487|                               dp->usb_wwid.interface);
 #  488|->                 format_ucs2(buf, size, off, "UsbWwid",
 #  489|                               dp->usb_wwid.serial_number, limit);
 #  490|                   format(buf, size, off, "UsbWwid", ")");

 Error: OVERRUN (CWE-119):
 efivar-38/src/dp-message.c:612: return_constant: Function call "efidp_node_size(dp)" may return -1.
 efivar-38/src/dp-message.c:612: overrun-buffer-arg: Calling "format_hex_helper" with "(uint8_t *)dp + 4" and "efidp_node_size(dp) - 4L" is suspicious because of the very large index, 18446744073709551611. The index may be due to a negative parameter being interpreted as unsigned.
 #  610|           default:
 #  611|                   format(buf, size, off, "Msg", "Msg(%d,", dp->subtype);
 #  612|->                 format_hex(buf, size, off, "Msg", (uint8_t *)dp+4,
 #  613|                                   efidp_node_size(dp)-4);
 #  614|                   format(buf, size, off, "Msg", ")");

This patch adds error checking to those uses of efidp_node_size().

Resolves: RHEL-27676
Signed-off-by: Peter Jones <pjones@redhat.com>