Add NO_THREADS variable
Allow the user to disable building thread-test to avoid the following
build failure without threads raised since version 38 and
https://github.com/rhboot/efivar/commit/cff88dd96b9d43e2c5875a24ba6180b196890ded:

thread-test.c:14:10: fatal error: pthread.h: No such file or directory
   14 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/277f783c33102a0cea7c82ca902119ab90f37ad4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>