efidp_format_device_path(): fix efidp_node_size() return value handling.
One of our internal scan tools noticed the following issues:

 Error: OVERRUN (CWE-119):
 efivar-38/src/dp.c:342: return_constant: Function call "efidp_node_size(dp)" may return -1.
 efivar-38/src/dp.c:342: overrun-buffer-arg: Calling "format_hex_helper" with "(uint8_t *)dp + 4" and "efidp_node_size(dp) - 4L" is suspicious because of the very large index, 18446744073709551611. The index may be due to a negative parameter being interpreted as unsigned.
 #  340|                                   format(buf, size, off, "BbsPath",
 #  341|                                          "BbsPath(%d,", dp->subtype);
 #  342|->                                 format_hex(buf, size, off, "BbsPath",
 #  343|                                              (uint8_t *)dp+4,
 #  344|                                              efidp_node_size(dp)-4);

 Error: OVERRUN (CWE-119):
 efivar-38/src/dp.c:374: return_constant: Function call "efidp_node_size(dp)" may return -1.
 efivar-38/src/dp.c:374: overrun-buffer-arg: Calling "format_hex_helper" with "(uint8_t *)dp + 4" and "efidp_node_size(dp) - 4L" is suspicious because of the very large index, 18446744073709551611. The index may be due to a negative parameter being interpreted as unsigned.
 #  372|                           format(buf, size, off, "Path",
 #  373|                                       "Path(%d,%d,", dp->type, dp->subtype);
 #  374|->                         format_hex(buf, size, off, "Path", (uint8_t *)dp + 4,
 #  375|                                      efidp_node_size(dp) - 4);
 #  376|                           format(buf, size, off, "Path", ")");

These are both in the same device path traversal loop.

This patch refactors that code to do the math and the error check at the
top of the loop.

Resolves: RHEL-27676
Signed-off-by: Peter Jones <pjones@redhat.com>