dp-media: more efidp_node_size() fixups.
In a prior commit, Leo fixed one of _format_media_dn()'s invocations of
efidp_node_size() to handle the failure case.  This patch builds on
that, using our more robust math primitives in that case.  There's also
a second analogous issue:

 Error: OVERRUN (CWE-119):
 efivar-38/src/dp-media.c:133: return_constant: Function call "efidp_node_size(dp)" may return -1.
 efivar-38/src/dp-media.c:133: overrun-buffer-arg: Calling "format_hex_helper" with "(uint8_t *)dp + 4" and "(efidp_node_size(dp) - 4L) / 2L" is suspicious because of the very large index, 18446744073709551614. The index may be due to a negative parameter being interpreted as unsigned.
 #  131|           default:
 #  132|                   format(buf, size, off, "Media", "MediaPath(%d,", dp->subtype);
 #  133|->                 format_hex(buf, size, off, "Media", (uint8_t *)dp+4,
 #  134|                                   (efidp_node_size(dp)-4) / 2);
 #  135|                   format(buf,size,off, "Media",")");

This patch fixes that case as well.

Resolves: RHEL-27676
Signed-off-by: Peter Jones <pjones@redhat.com>