Fix some allocation bounds checking gcc 7.x finds sometimes.
gcc 7.0.1 has -Walloca-larger-than=N and -Walloc-size-larger-than=N
flags that -O2 enables now, and they try to bounds check arguments to
alloca() and malloc().

Unfortunately they have horrible error messages, so you get:

dp-message.c: In function ‘_format_message_dn’:
dp-message.c:422:9: error: argument 1 range [9223372036854775809, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
   addr0 = alloca(sz+1);
         ^
dp-message.c:422:9: note: in a call to built-in allocation function ‘__builtin_alloca’

When what it means is:

 Check for error you nitwit.  Now I'm going to tell you a pile of math
 we did that isn't useful to you at all.

And also:

dp-message.c:466:3: error: argument 1 value ‘18446744073709551606’ exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
   format_ucs2(buf, size, off, "UsbWwid",
   ^
dp-message.c:466:3: note: in a call to built-in allocation function ‘__builtin_alloca_with_align’
dp-message.c:466:3: error: ‘memset’: specified size 18446744073709551606 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
dp-message.c:466:3: error: ‘memcpy’: specified size 18446744073709551604 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

Which actually means:

 You accidentally made the predicating check for bounds be against a
 signed value Now I'm going to tell you a pile of useless data about
 where you later used the result instead of telling you about the
 problem.

Anyway, this fixes it.

Signed-off-by: Peter Jones <pjones@redhat.com>