Fix an argument mismatch error
MSDOS_MBR_MAGIC is an int, no need to specify the 'h' (unsigned short)
modifier. This avoids the error (built with clang):

external/efivar/src/disk.c:59:18: error: format specifies type 'unsigned short' but the argument has type 'int' [-Werror,-Wformat]
                          mbr->magic, MSDOS_MBR_MAGIC);
                                      ^~~~~~~~~~~~~~~
external/efivar/src/include/efivar/efivar.h:244:66: note: expanded from macro 'efi_error'
        efi_error_real__(errno, __FILE__, __func__, __LINE__, (fmt), ## args)
                                                                        ^~~~
external/efivar/src/include/efivar/efivar.h:241:56: note: expanded from macro 'efi_error_real__'
        efi_error_set(file, function, line, errval, (fmt), ## args)
                                                              ^~~~
external/efivar/src/gpt.h:32:25: note: expanded from macro 'MSDOS_MBR_MAGIC'
 #define MSDOS_MBR_MAGIC 0xaa55
                        ^~~~~~
1 error generated.

Fixes: 038afd7a ("Always refer to MBR and GPT fixed values as 'magic' not 'signature'")

Signed-off-by: Chih-Wei Huang <cwhuang@linux.org.tw>