dp.h: Fix incorrect efidp_node_size() error handling
One of our internal analysis tools noticed the following:

 Error: OVERRUN (CWE-119):
 efivar-38/src/dp.h:104: return_constant: Function call "efidp_node_size(dp)" may return -1.
 efivar-38/src/dp.h:104: assignment: Assigning: "bytes" = "efidp_node_size(dp) - 4UL - 16UL". The value of "bytes" is now -21.
 efivar-38/src/dp.h:112: overrun-buffer-arg: Calling "format_hex_helper" with "dp->hw_vendor.vendor_data" and "bytes" is suspicious because of the very large index, 18446744073709551595. The index may be due to a negative parameter being interpreted as unsigned.
 #  110|           if (bytes) {
 #  111|                   format(buf, size, off, label, ",");
 #  112|->                 format_hex(buf, size, off, label, dp->hw_vendor.vendor_data,
 #  113|                              bytes);
 #  114|           }

This patch corrects the error checking for the efidp_node_size()
invocation, so the code will never get this far if it errors.

Resolves: RHEL-27676
Signed-off-by: Peter Jones <pjones@redhat.com>