Fix wrong variadic initialization
One of our internal scanning tools found the following error:

 Error: VARARGS (CWE-237):
 efivar-38/src/creator.c:227: va_arg: Calling va_arg on va_list "aq", which has not been prepared with va_start().
 #  225|                   va_copy(aq, ap);
 #  226|
 #  227|->                 dev->edd10_devicenum = va_arg(aq, uint32_t);
 #  228|
 #  229|                   va_end(aq);

I have no idea what the code in efi_va_generate_file_device_path_from_esp()
was trying to do, but as far as I can tell we shouldn't need to do
anything special to access the variadic arguments.

This patch takes most of that code out.

Resolves: RHEL-27676
Signed-off-by: Peter Jones <pjones@redhat.com>