Remove -fshort-wchar from CFLAGS
-fshort-wchar makes wchar_t 16bit. We are not using wchar_t anywhere,
so we don't need it. Removing it fixes an compilation error with musl
libc:

In file included from dp-acpi.c:21:0:
/usr/lib/gcc/armv7a-hardfloat-linux-musleabi/4.7.4/include/stddef.h:325:24: error: conflicting types for ‘wchar_t’
In file included from /usr/include/inttypes.h:12:0,
                 from dp-acpi.c:20:
/usr/include/bits/alltypes.h:18:18: note: previous declaration of ‘wchar_t’ was here
make[1]: *** [dp-acpi.o] Error 1
make: *** [src] Error 2