Remove an unused function
This gets rid of an error from Android 9 clang:

external/efivar/src/linux.c:256:1: error: unused function 'supports_iface' [-Werror,-Wunused-function]
supports_iface(struct dev_probe *probe, enum interface_type iftype)
^
1 error generated.

Signed-off-by: Chih-Wei Huang <cwhuang@linux.org.tw>